### ISSUE TITLE
无法登录，显示failed

### ISSUE THREAD

**Issue by smile31768** [2697a/bujuan#10]
网易云疑似更换接口，隔壁倒带也无法登录网易云，隔壁是显示网络拥挤

**Comment by 2697a** [comment]
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/24308269/175886342-6a36fc8a-8afb-455b-ba1d-06427c9015ed.png">
目前我正在申请使用官方开放出来的api,通过之后我会更新相应接口的

**Comment by smile31768** [comment]
> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/24308269/175886342-6a36fc8a-8afb-455b-ba1d-06427c9015ed.png">
> 
> 目前我正在申请使用官方开放出来的api,通过之后我会更新相应接口的

收到！感谢大佬坚持维护！

**Comment by i35010u** [comment]
> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/24308269/175886342-6a36fc8a-8afb-455b-ba1d-06427c9015ed.png">
> 
> 目前我正在申请使用官方开放出来的api,通过之后我会更新相应接口的

请问通过了吗？
