### ISSUE TITLE
出现armv8a版本播放无声，armv7a版本正常的情况

### ISSUE THREAD

**Issue by ketsurineko** [2697a/bujuan#16]
软件版本：2.0.4
设备：fiio M11 
安卓7.1 SOC Exynos 7872
两个版本安装后均能打开，但是armv8a版本无声。
个人理解支持64位的ARM设备应该就没什么问题，所以我想发这个issue问一下是什么原因导致的这个问题。

**Comment by ketsurineko** [comment]
测试了一下不是这个问题。。。

**Comment by 2697a** [comment]
> 测试了一下不是这个问题。。。

好的
