### ISSUE TITLE
通知 bug

### ISSUE THREAD

**Issue by xiaocheng168** [2697a/bujuan#19]
![Screenshot_20230712_212148.jpg](https://github.com/2697a/bujuan/assets/43944975/917e86a7-1d28-4301-930b-15eda9ad1143)

![Screenshot_20230712_212226.jpg](https://github.com/2697a/bujuan/assets/43944975/7993f30f-5f5e-42d3-8c3f-7a659dd94f64)

使用私人 FM 听歌 通知标题含有未解析的 json 原数据
其他的暂未发现

**Comment by 2697a** [comment]
这个已经修复，下次更新就正常了

**Comment by xiaocheng168** [comment]
> 这个已经修复，下次更新就正常了

支持作者
