### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by stlion** [2697a/bujuan#2]
邮箱+密码登录，提示fail，不能登录。

**Comment by stlion** [comment]
版本是105和108（APP内写107的，在酷安找到的链接）。

**Comment by 2697a** [comment]
> 版本是105和108（APP内写107的，在酷安找到的链接）。
登录应该是没问题的，去网易修改一下密码应该就可以了

**Comment by RGthx** [comment]
手机号与密码登录
无法登录
尝试更换密码，无效
尝试更换api低版本，也无效
或许是api接口出问题了？！

**Comment by 2697a** [comment]
版本已更新
