### ISSUE TITLE
关于两文字图层未做隔离

### ISSUE THREAD

**Issue by hahaha3542** [2697a/bujuan#24]
在很多界面页面标题图层和列表图层两段文字没有隔离导致内容混合在了一起，如图
![Screenshot_20230716_184646_com sixbugs bujuan](https://github.com/2697a/bujuan/assets/69064412/13f33439-99e5-49f3-a2a3-59f8bc9dca4d)

**Comment by 2697a** [comment]
新版本已做处理，请等待更新哈
