### ISSUE TITLE
安卓分层图标颜色问题

### ISSUE THREAD

**Issue by FlysoftBeta** [2697a/bujuan#25]
![Screenshot_20230716_193442_com sixbugs bujuan](https://github.com/2697a/bujuan/assets/49718840/511f168d-9974-459b-8d78-314dcef6651e)
如图，应用退出时应用图标后是绿色的

**Comment by 2697a** [comment]
好的 我下次更新修复

**Comment by hahaha3542** [comment]
总感觉是MIUI特化后的问题，我HMos没出现这种问题

**Comment by FlysoftBeta** [comment]
> 总感觉是MIUI特化后的问题，我HMos没出现这种问题

然而我这个就是鸿蒙🤔

**Comment by hahaha3542** [comment]
哦我仔细看了下我这边也有发现

**Comment by hahaha3542** [comment]
> > 总感觉是MIUI特化后的问题，我HMos没出现这种问题
> 
> 然而我这个就是鸿蒙🤔

哦我看了一下确实有，要仔细看
