### ISSUE TITLE
【无法登陆】应用登录提示网络繁忙

### ISSUE THREAD

**Issue by Rueile** [2697a/bujuan#36]
![Screenshot_2023-09-24-11-56-39-399_com sixbugs bujuan-edit](https://github.com/2697a/bujuan/assets/145895045/7f0880d8-1637-4056-922d-5c27e12cc281)

**Comment by 2697a** [comment]
> ![Screenshot_2023-09-24-11-56-39-399_com sixbugs bujuan-edit](https://user-images.githubusercontent.com/145895045/270151133-7f0880d8-1637-4056-922d-5c27e12cc281.jpg)

我刚才用2.0.4登录是正常的，你可以试试扫码或者修改一下密码

**Comment by Rueile** [comment]
扫码进去了。不过里面歌曲不显示专辑封面欸。
![Uploading Screenshot_2023-09-25-15-03-27-904_com.sixbugs.bujuan.jpg…]()

**Comment by 2697a** [comment]
<img width="923" alt="image" src="https://github.com/2697a/bujuan/assets/24308269/790ea11e-c1ee-436f-935a-83275b9fbb84">
zhe ge这个已经修复，不过还没打包更新

**Comment by Rueile** [comment]
OK，感谢

**Comment by Tim8888888** [comment]
不能挂vpn

**Comment by 2697a** [comment]
图片问题已修复，新版本已提交
