### ISSUE TITLE
音乐图片在正常网络环境无法加载，挂上VPN后正常图片加载，稳定复现

### ISSUE THREAD

**Issue by Brconn** [2697a/bujuan#39]
![Screenshot_2023-10-08-18-06-24-615_com sixbugs bu](https://github.com/2697a/bujuan/assets/111224204/639ff935-db9c-4937-8bf0-6ca87fa5eef9)
![Screenshot_2023-10-08-18-08-37-872_com sixbugs bu](https://github.com/2697a/bujuan/assets/111224204/bb441fb2-a541-42ab-8752-7069e60196b1)

**Comment by Brianwind** [comment]
我看到作者在两周前已经处理了图片403的bug，希望能重新发布一版release。

**Comment by 2697a** [comment]
最近工作太忙了，我会尽快更新的

**Comment by Meilinhost** [comment]
我也遇到了
![Screenshot_20231020-060131__01](https://github.com/2697a/bujuan/assets/3524108/653cd127-241b-4dcf-b255-4bb9fd7a6cb9)

**Comment by ShenJason99629** [comment]
我下载的2.0.4也遇到了同样的问题，而且貌似挂了梯子也没能显示。希望作者早日抽空修复bug。谢谢

**Comment by UnspokenSpell** [comment]
> 最近工作太忙了，我会尽快更新的

![2023-12-11_21-43-03](https://github.com/2697a/bujuan/assets/73733485/c5c943c9-99f8-44f1-968b-7c512d9d2d5e)

建议学习一下GitHub的Action，可以**自动**打包程序

**Comment by UnspokenSpell** [comment]
> 我下载的2.0.4也遇到了同样的问题，而且貌似挂了梯子也没能显示。希望作者早日抽空修复bug。谢谢

你让网易云音乐的流量走代理了吗？一般情况下，代理的规则会将国内的应用的流量定向到"直连"。
试试全局模式。

**Comment by ShenJason99629** [comment]
> > 我下载的2.0.4也遇到了同样的问题，而且貌似挂了梯子也没能显示。希望作者早日抽空修复bug。谢谢
> 
> 你让网易云音乐的流量走代理了吗？一般情况下，代理的规则会将国内的应用的流量定向到"直连"。 试试全局模式。

确实如你所说，设置让bujuan走代理之后，就能显示了

**Comment by 2697a** [comment]
2.0.5已更新release
