### ISSUE TITLE
报告：不动其他设置，有些歌曲播放的时候有声音但是有些歌曲播放的时候没有声音。

### ISSUE THREAD

**Issue by gosleeper** [2697a/bujuan#41]
没有声音的歌曲：达尔文【林俊杰】；一千公里（live）【张杰/杨和苏keyng】；年轮说【吴青峰】，，这些听不了声音的歌曲也不算少，还有图片也刷不出来。

**Comment by 2697a** [comment]
图片的已经好了

**Comment by 2697a** [comment]
> 没有声音的歌曲：达尔文【林俊杰】；一千公里（live）【张杰/杨和苏keyng】；年轮说【吴青峰】，，这些听不了声音的歌曲也不算少，还有图片也刷不出来。

进度条正常吗？

**Comment by gosleeper** [comment]
感谢，感谢，现在用着没什么问题
