### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Brianwind** [2697a/bujuan#43]
作者一直没有更新图片问题的修复，于是我想来自己编译一个，但是发现编译出错了
**我对Flutter和Rust完全是新手，所以只做了基本的环境配置，没有做任何代码修改**
即，我只安装了flutter、rust和flutter_rust_bridge_codegen（但没有用它来生成代码）

希望作者或者有没有其他人（如果有空的话）能帮忙看看为啥出了问题

## 出错Log
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

One or more plugins require a higher Android NDK version.
Fix this issue by adding the following to /home/yizhou/Projects/bujuan/android/app/build.gradle:
android {
  ndkVersion "25.1.8937393"
  ...
}

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
lib/pages/home/home_controller.dart:44:7: Error: The non-abstract class 'Home' is missing implementations for these members:
 - FullLifeCycleMixin.onHidden
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class Home extends SuperController with GetSingleTickerProviderStateMixin {
      ^^^^
../../.pub-cache/hosted/pub.flutter-io.cn/get-4.6.6/lib/get_state_manager/src/simple/get_controllers.dart:126:8: Context: 'FullLifeCycleMixin.onHidden' is defined here.
  void onHidden();
       ^^^^^^^^
lib/common/netease_api/src/encrypt_ext.dart:95:13: Error: The method 'RSAExt.encrypt' has fewer named arguments than those of overridden method 'Algorithm.encrypt'.
  Encrypted encrypt(Uint8List bytes, {IV? iv}) {
            ^
../../.pub-cache/hosted/pub.flutter-io.cn/encrypt-5.0.3/lib/src/algorithm.dart:6:13: Context: This is the overridden method ('encrypt').
  Encrypted encrypt(Uint8List bytes, {IV? iv, Uint8List? associatedData});
            ^
lib/common/netease_api/src/encrypt_ext.dart:95:13: Error: The method 'RSAExt.encrypt' doesn't have the named parameter 'associatedData' of overridden method 'Algorithm.encrypt'.
  Encrypted encrypt(Uint8List bytes, {IV? iv}) {
            ^
../../.pub-cache/hosted/pub.flutter-io.cn/encrypt-5.0.3/lib/src/algorithm.dart:6:13: Context: This is the overridden method ('encrypt').
  Encrypted encrypt(Uint8List bytes, {IV? iv, Uint8List? associatedData});
            ^
lib/common/netease_api/src/encrypt_ext.dart:108:13: Error: The method 'RSAExt.decrypt' has fewer named arguments than those of overridden method 'Algorithm.decrypt'.
  Uint8List decrypt(Encrypted encrypted, {IV? iv}) {
            ^
../../.pub-cache/hosted/pub.flutter-io.cn/encrypt-5.0.3/lib/src/algorithm.dart:9:13: Context: This is the overridden method ('decrypt').
  Uint8List decrypt(Encrypted encrypted, {IV? iv, Uint8List? associatedData});
            ^
lib/common/netease_api/src/encrypt_ext.dart:108:13: Error: The method 'RSAExt.decrypt' doesn't have the named parameter 'associatedData' of overridden method 'Algorithm.decrypt'.
  Uint8List decrypt(Encrypted encrypted, {IV? iv}) {
            ^
../../.pub-cache/hosted/pub.flutter-io.cn/encrypt-5.0.3/lib/src/algorithm.dart:9:13: Context: This is the overridden method ('decrypt').
  Uint8List decrypt(Encrypted encrypted, {IV? iv, Uint8List? associatedData});
            ^
lib/pages/setting/image_blur.dart:118:33: Error: Property 'buffer' cannot be accessed on 'ByteData?' because it is potentially null.
 - 'ByteData' is from 'dart:typed_data'.
Try accessing using ?. instead.
    completer.complete(byteData.buffer.asUint8List());
                                ^^^^^^
lib/bridge_generated.dart:33:57: Error: Required named parameter 'parseErrorData' must be provided.
    return _platform.executeNormal(FlutterRustBridgeTask(
                                                        ^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_rust_bridge-1.82.4/lib/src/basic.dart:172:9: Context: Found this candidate, but the arguments don't match.
  const FlutterRustBridgeTask({
        ^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/home/yizhou/Programs/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/yizhou/Programs/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
Running Gradle task 'assembleRelease'...                           94.4s
Gradle task assembleRelease failed with exit code 1

**Comment by 2697a** [comment]
我来编译吧

**Comment by 2697a** [comment]
已编译，2.0.5已上传release

**Comment by wlya** [comment]
同这个问题，有什么解么？
