### ISSUE TITLE
建议适配平板

### ISSUE THREAD

**Issue by 610364023** [2697a/bujuan#45]
我用平板UI都挤在一起。
上面有圆角。
强制横屏后显示空白。
![Screenshot_2023-12-14-11-26-20-692_com sixbugs bujuan](https://github.com/2697a/bujuan/assets/45279039/fd384baf-6c24-4670-b2b6-6e58fe05b9fe)
![Screenshot_2023-12-14-11-23-59-745_com sixbugs bujuan](https://github.com/2697a/bujuan/assets/45279039/f7de11e4-c352-4022-a767-d0fabf216a6b)
![IMG_20231214_112553](https://github.com/2697a/bujuan/assets/45279039/60416cad-32a6-4012-8fb8-81dc41c0c7f6)

**Comment by 2697a** [comment]
正在适配，到时候平板会强制横屏
