### ISSUE TITLE
遇到无版权歌曲虽然不变灰但是会自动跳过无法播放

### ISSUE THREAD

**Issue by JKSerika** [2697a/bujuan#48]
换安卓14系统了，特别想继续拥有灰色歌曲匹配功能QAQ，lspatch一打包网易云就闪退，要是这边能继续有这功能就太好了，这边还简洁！不过目前还是没法进行匹配，求救QAQ

**Comment by 2697a** [comment]
现在是这样的，没版权的歌曲在2.0.5上面无法播放，灰色歌曲匹配功能目前还在试验阶段
