### ISSUE TITLE
控制中心的播放模块未能更新信息

### ISSUE THREAD

**Issue by UnspokenSpell** [2697a/bujuan#53]
新版的通知与控制中心的控制中心有一个显示播放信息的模块，在最下方。

## 问题

![IMG_20240121_193428](https://github.com/2697a/bujuan/assets/73733485/f9ecb584-dcb2-471b-a320-c7649dc28971)
当BuJuan的播放进入下一首之后，此模块未能更新歌曲信息，而是显示“暂无播放”。经过实测，网易云音乐可以使此模块正常更新信息

### 预期表现
当BuJuan的播放进入下一首之后，此模块更新歌曲信息。

## 环境
安卓版本：**13**
系统版本：MIUI **14**

**Comment by xfrqh** [comment]
我不用这个模块，修不修无所谓。😝

**Comment by UnspokenSpell** [comment]
我不用这个模块，修不修无所谓。😝
