### ISSUE TITLE
适配LyricsGetter

### ISSUE THREAD

**Issue by ghost** [2697a/bujuan#54]
### **希望可以适配LyricsGetter。**

> 目前LyricGetterExt扩展可以从网络上获取歌词，但其与MIUI不适配。

> 由于MIUI的妙播bug（之前的issues中有），会导致切换到下一首歌曲时，从MediaController中获取的当前正在播放的媒体信息为空，进而导致LyricGetterExt工作异常。

> 如果能够原生适配LyricsGetter，那就不需要绕一大圈去获取歌词，同时能使歌词更加准确。

**Comment by 2697a** [comment]
感谢您的建议，目前的主要工作是适配横屏和状态管理库的迁移
