### ISSUE TITLE
v2.0.5的BUG反馈和建议

### ISSUE THREAD

**Issue by MieLittlesheep** [2697a/bujuan#57]
制作不易，感谢APP。斗胆在此反馈几个BUG。
1.在播放时，一直点返回到关闭界面，有可能直接停止播放，而不会在后台继续播放，但有时候又不会。

2.在单曲循环状态下，点击上下首，并不会切歌，而是从头播放这一条曲目。

另外几个建议向您请教，您可以考虑看看能否进行改进：

1.在播放列表和歌单中显示歌曲的中文名（如果有）。比如说一些日文歌名后面有些自带中文名的，打个括号里面写上中文名。

2.在播放列表和歌单中，可以设置在歌手后带上专辑名。

3.在歌曲进度条界面，点击封面可以直接跳转到歌词页，而非必须点双引号才能进。

4.在播放列表和歌单中增加一个能定位当前播放曲目的按钮，或者在某个位置显示当前正在播放的歌曲在歌单或播放列表中的序号方便快速查找。

5.退出时能记住当前播放进度。

6.增加音频冲突时能够继续播放的设置（应用场景：比如进入游戏，会有游戏的BGM，这时软件的音乐就会停止，只能手动再重新开始。就是希望可以不用手动再去点开始）

非常感谢您能耐心看完，内容如有不妥，还请见谅。

**Comment by 2697a** [comment]
> 制作不易，感谢APP。斗胆在此反馈几个BUG。 1.在播放时，一直点返回到关闭界面，有可能直接停止播放，而不会在后台继续播放，但有时候又不会。
> 
> 2.在单曲循环状态下，点击上下首，并不会切歌，而是从头播放这一条曲目。
> 
> 另外几个建议向您请教，您可以考虑看看能否进行改进：
> 
> 1.在播放列表和歌单中显示歌曲的中文名（如果有）。比如说一些日文歌名后面有些自带中文名的，打个括号里面写上中文名。
> 
> 2.在播放列表和歌单中，可以设置在歌手后带上专辑名。
> 
> 3.在歌曲进度条界面，点击封面可以直接跳转到歌词页，而非必须点双引号才能进。
> 
> 4.在播放列表和歌单中增加一个能定位当前播放曲目的按钮，或者在某个位置显示当前正在播放的歌曲在歌单或播放列表中的序号方便快速查找。
> 
> 5.退出时能记住当前播放进度。
> 
> 6.增加音频冲突时能够继续播放的设置（应用场景：比如进入游戏，会有游戏的BGM，这时软件的音乐就会停止，只能手动再重新开始。就是希望可以不用手动再去点开始）
> 
> 非常感谢您能耐心看完，内容如有不妥，还请见谅。

谢谢您的建议。由于使用的框架已停止更新，目前正在迁移，这些bug会在后续修复！
