### ISSUE TITLE
上架F-Droid及更新Release

### ISSUE THREAD

**Issue by xuangeyouneihan** [2697a/bujuan#7]
如题，感觉总在酷安发布下载链接，Release停在1.0.5也不是个事。语气可能不太好，抱歉

**Comment by 2697a** [comment]
> 总

没事没事，酷安上架会被拒的，release一会我更新一下哈

**Comment by xuangeyouneihan** [comment]
那试试上架F-Droid？

**Comment by 2697a** [comment]
> 那试试上架F-Droid？
> […](#)
> On April 16, 2022 3:05:23 PM GMT+08:00, sixbugs ***@***.***> wrote: > 总 没事没事，酷安上架会被拒的，release一会我更新一下哈 -- Reply to this email directly or view it on GitHub: [#7 (comment)](https://github.com/2697a/bujuan/issues/7#issuecomment-1100591114) You are receiving this because you authored the thread. Message ID: ***@***.***>

最新release已经上传了，F-Droid的我看下吧

**Comment by xuangeyouneihan** [comment]
顺带一提，更新的时候能不能开一个新的release？那样的话在“Watch”里点击“Custom”选择“Releases”可以方便地通过邮箱收到更新。谢谢！

于 2022年4月16日 GMT+08:00 下午6:27:29, sixbugs ***@***.***> 写到:

**Comment by 2697a** [comment]
> 

好的

**Comment by linsui** [comment]
@2697a 我可以给 F-Droid 打包吗？
