### ISSUE TITLE
关于UI的问题

### ISSUE THREAD

**Issue by NightIeep** [2697a/bujuan#71]
能不能出个调整播放界面调整专辑封面大小的功能，因为这个东西在手表端上会挤压进度条、歌词、评论区和暂停等按钮，向上滑动打开歌词页面虽然歌词、评论区、暂停都可以用了，但进度条和播放顺序还是无法调整，影响使用了，求修复
(Ps:身为开发者的你要知道，Bujuan的低性能要求、UI简洁美观和高兼容性在手表上是很好的一款应用，可惜UI好看但是在播放界面有如上Bug，故提出请求)
[还有可以的话，请不要砍掉本地播放功能，求求了，也许这个可以参考一下"零度音乐"？(我是纯门外汉，一个普通用户)]

**Comment by M0ONX** [comment]
> 能不能出个调整播放界面调整专辑封面大小的功能，因为这个东西在手表端上会挤压进度条、歌词、评论区和暂停等按钮，向上滑动打开歌词页面虽然歌词、评论区、暂停都可以用了，但进度条和播放顺序还是无法调整，影响使用了，求修复 (Ps:身为开发者的你要知道，Bujuan的低性能要求、UI简洁美观和高兼容性在手表上是很好的一款应用，可惜UI好看但是在播放界面有如上Bug，故提出请求) [还有可以的话，请不要砍掉本地播放功能，求求了，也许这个可以参考一下"零度音乐"？(我是纯门外汉，一个普通用户)]

![Uploading IMG_20240609_163030.jpg…]()
![Uploading IMG_20240609_163049.jpg…]()

**Comment by M0ONX** [comment]
> 能不能出个调整播放界面调整专辑封面大小的功能，因为这个东西在手表端上会挤压进度条、歌词、评论区和暂停等按钮，向上滑动打开歌词页面虽然歌词、评论区、暂停都可以用了，但进度条和播放顺序还是无法调整，影响使用了，求修复 (Ps:身为开发者的你要知道，Bujuan的低性能要求、UI简洁美观和高兼容性在手表上是很好的一款应用，可惜UI好看但是在播放界面有如上Bug，故提出请求) [还有可以的话，请不要砍掉本地播放功能，求求了，也许这个可以参考一下"零度音乐"？(我是纯门外汉，一个普通用户)]

**Comment by M0ONX** [comment]
> 能不能出个调整播放界面调整专辑封面大小的功能，因为这个东西在手表端上会挤压进度条、歌词、评论区和暂停等按钮，向上滑动打开歌词页面虽然歌词、评论区、暂停都可以用了，但进度条和播放顺序还是无法调整，影响使用了，求修复 (Ps:身为开发者的你要知道，Bujuan的低性能要求、UI简洁美观和高兼容性在手表上是很好的一款应用，可惜UI好看但是在播放界面有如上Bug，故提出请求) [还有可以的话，请不要砍掉本地播放功能，求求了，也许这个可以参考一下"零度音乐"？(我是纯门外汉，一个普通用户)]
