### ISSUE TITLE
安装完一天后无法加载每日推荐和我喜欢的音乐

### ISSUE THREAD

**Issue by xuangeyouneihan** [2697a/bujuan#8]
### 如题，到设置中的应用详情页面清除缓存不管用，只有将数据全部删除重置应用才能好使（然后还得重新登录），怀疑与网易云第二天发布的每日推荐有关。  
- 应用版本：1.1.0
- 系统版本：鸿蒙2.0.0（安卓内核为10）

![Screenshot_20220417_093518_com sixbugs bujuan](https://user-images.githubusercontent.com/50788434/163700352-1206c68e-0845-4787-b8fd-3f84af33d2c8.jpg)

**Comment by 2697a** [comment]
重新登录一下试试，应该是bug
