### ISSUE TITLE
网易云风控问题

### ISSUE THREAD

**Issue by KoishiMoe** [2697a/bujuan#83]
据[上游的相关报告](https://gitlab.com/Binaryify/neteasecloudmusicapi/-/issues/25)，网易似乎在近期加强了风控措施，我想确认一下bujuan是否也会受到这一问题的影响，以及近期是否可能会有对应的更新，谢谢！

**Comment by 2697a** [comment]
应该会影响，近期会开始慢慢更新，适配完新版本sdk，我开始着手看这个

**Comment by dissipator** [comment]
实在解决不了建议开启一个uid拉去歌单的方案
